Additional RPC scaffolding
kaspanet/rusty-kaspa pull request #102
Opened 2023-01-13 13:49 UTC by aspect

This PR includes message structs and routing for additional RPC functions.

2023-01-15 23:07 UTC, tiram88 requested changes
- I addressed you questions.
- In substance, almost all good.
- Nice macros. The paste crate is of great help, I'm fan!
- Some more cleanup is welcome.
- Formally just a few points to better comply with our coding (though non explicit) rules, if you don't mind.

Note that the mining demo is broken but this does not come from your code. I checked in my mempool branch and got same result. The problem lies in the consensus (consensus\src\pipeline\virtual_processor\processor.rs).

2023-01-16 02:46 UTC, aspect commented on consensus/core/src/networktype.rs
> +use addresses::Prefix;
I am following rust standards (that recommend against this) followed in say consensus module, such as blockhash and blockstatus.

2023-01-16 02:54 UTC, aspect commented on rpc/core/src/api/rpc.rs
> +    async fn get_mempool_entry_call(&self, request: GetMempoolEntryRequest) -> RpcResult<GetMempoolEntryResponse>;
I was just not sure if this is something that should be done.  In my original design this is not something I had.  Do you intend on having each function accept parametric arguments?  and also have message structs have constructors?  that's a lot of redundant code, whereas I am against constructors and RPC functions arguments (for all but fns that have no args), so I am somewhat staying away from all that overhead :)

2023-01-16 03:15 UTC, aspect commented on rpc/core/src/error.rs
> -pub type RpcResult<T> = std::result::Result<T, crate::RpcError>;
Moved the `Result` back to `error`.  In my practice, there are various benefits of segregating results from errors and many mainstream crates do this. this is more of an "unformulated rust practice", but varies from crate to crate.

2023-01-16 03:23 UTC, aspect commented on rpc/core/src/model/networktype.rs
> +pub type RpcNetworkType = consensus_core::networktype::NetworkType;
I followed naming convention in consensus such as `blockhash.rs` etc.  Moved this discussion to TG for the time being

2023-01-16 03:26 UTC, aspect commented on rpc/core/src/model/peer.rs
> +    // FIXME type
Oh, I seem to have forgotten to bring that up in telegram - I left FIXME markers specifically for you to fix types where I don't know what the types should be.

2023-01-16 04:08 UTC, aspect commented on rpc/grpc/src/client/route.rs
> +macro_rules! route {
Note: this macro is an extract of the function generated by the `#[async_trait]` as implementing a simple fn definition using basic macros was not working combined with the `#[async_trait]` attribute macro.

2023-01-16 12:00 UTC, michaelsutton approved these changes

2023-01-16 12:00 UTC, merged