Complete IBD & Relay Flows
kaspanet/rusty-kaspa pull request #138
Opened 2023-03-06 10:04 UTC by michaelsutton

Some minor details are still wip

2023-03-12 21:48 UTC, someone235 requested changes

2023-03-13 10:21 UTC, michaelsutton commented on consensus/src/consensus/mod.rs
> +        self.counters.blocks_submitted.fetch_add(1, Ordering::Relaxed);
For counting purposes there is no need for any memory ordering guarantees, We simply need best effort atomic counting

2023-03-13 10:22 UTC, michaelsutton commented on kaspad/src/main.rs
> +    let _mining_manager =
I prefer that we keep it until @tiram88 integrates it properly

2023-03-13 10:27 UTC, michaelsutton commented on consensus/src/pipeline/deps_manager.rs
> +    task: Option<BlockTask>,
When a worker calls `try_begin` the task is taken out. This avoids a clone + it allows better error tracking/reports if users misuse this API (on `end` we verify the task was taken)

2023-03-14 12:12 UTC, someone235 requested changes

2023-03-14 12:25 UTC, someone235 approved these changes

2023-03-14 12:46 UTC, merged