Multi-consensus Management, Staging Consensus, Consensus Sessions
kaspanet/rusty-kaspa pull request #148
Opened 2023-03-28 14:45 UTC by michaelsutton

Implements support for multiple consensus instances managed through a management-level DB. As a private case this includes support for staging consensus (which is used during an headers-proof IBD). The PR also includes API support for consensus read-sessions, which are essential for the soon-coming pruning implementation. 

Still **wip** and with bugs, but nonetheless the design should start being reviewed.

The reader should focus on the external API of `ConsensusManager` and on the usages of current/staging consensus in the various P2P flows and in the UTXO index/RPC service.

2023-04-02 16:38 UTC, someone235 requested changes

2023-04-02 16:38 UTC, someone235 commented on rpc/service/Cargo.toml
> +# faster-hex.workspace = true
Can you remove redundant comments?

2023-04-03 09:29 UTC, michaelsutton commented on consensus/src/consensus/factory.rs
> +        // TODO: pass lock to consensus
yes

2023-04-03 09:56 UTC, michaelsutton commented on consensus/src/consensus/ctl.rs
> +    fn make_active(&self) {
it's kind of a more contextual name for this specific instance. Make this one the active one, without knowledge of the staging concept

2023-04-04 11:52 UTC, someone235 approved these changes

2023-04-04 11:52 UTC, merged