"Implement file descriptor budget pool"
kaspanet/rusty-kaspa pull request #284
Opened 2023-09-25 10:15 UTC by biryukovmaxim

In this commit, a file descriptor budget pool has been implemented for better allocation of file descriptors. The feature has been added in a new library named "fd_budget_pool".

The implementation uses atomic operations to keep track of acquired file descriptors and ensures that the total number of acquired descriptors never exceeds a system-specific limit. A FDGuard structure was introduced to automatically release the acquired file descriptors when they are no longer in use. The ordering of atomic operations is marked as 'to do' for later optimization considerations. The get_limit function will check the system and determine the maximum allowable file descriptors.

Additionally, tests are written to confirm the correct functioning of the feature. Changes have also been made to Cargo files to include the new library and its dependencies. The ultimate goal of this feature is to prevent system-level issues arising from exhausting file descriptors.

2023-10-25 14:10 UTC, someone235 requested changes

2023-10-25 14:16 UTC, biryukovmaxim commented on utils/src/fd_budget.rs
> +            panic!("unsupported OS")
in readme there is info only about windows/macos/linux. why anyone else would call this fn?

2023-10-25 14:17 UTC, biryukovmaxim commented on kaspad/src/main.rs
> +    let fd_total_budget = get_limit() - 64;
yes it is for network connections, I will decrease it to 32

2023-10-25 14:23 UTC, someone235 commented on utils/src/fd_budget.rs
> +            panic!("unsupported OS")
I would prefer that if someone wanna run it with some weird OS it will run and not crash

2023-10-27 08:32 UTC, biryukovmaxim commented on kaspad/src/main.rs
> +    let fd_total_budget = get_limit() - 64;
now it is `    let fd_total_budget = limit() - args.rpc_max_clients - args.inbound_limit - args.outbound_target;`

2023-10-29 10:47 UTC, someone235 requested changes

2023-10-29 10:47 UTC, someone235 commented on kaspad/src/main.rs
> +    let fd_total_budget = limit() - args.rpc_max_clients as i32 - args.inbound_limit as i32 - args.outbound_target as i32;
I think it's more readable to write `fd_budget::limit()` (here and in other places)

2023-10-29 11:32 UTC, someone235 approved these changes

2023-10-29 12:08 UTC, merged