Add UPnP support and configurations to Kaspad
kaspanet/rusty-kaspa pull request #288
Opened 2023-09-30 16:59 UTC by biryukovmaxim

Introduced Universal Plug and Play (UPnP) configurations in the Kaspad system to automatically forward ports on a broadband router. The UPnP setting is optional and can be configured via the 'kaspad/src/args.rs' file. The 'upnp' field was added to 'Config' structs and default configuration was set as 'false'. A function was added to map ports if UPnP is enabled and the 'igd-next' library was incorporated to facilitate UPnP support. The changes improve Kaspad's peer discovery mechanism by allowing it to be accessed by more peers especially when behind a NAT firewall.

2023-10-01 17:33 UTC, coderofstuff requested changes

2023-10-01 17:33 UTC, coderofstuff commented on kaspad/src/args.rs
> +    ).arg(arg!(--upnp "Enable upnp"));
Can we make upnp enabled by default?

Then flag here can be `--disable-upnp` which disables the implementation. Ideally, the base `kaspad --utxoindex` will do the upnp check.

2023-10-19 19:20 UTC, coderofstuff commented on components/addressmanager/src/port_mapping_extender.rs
> +                .unwrap(); // todo handle??
Definitely needs to be handled. Currently can cause the node to panic.

Replication:
1. Start the node
2. Turn off your wifi

2023-10-23 13:09 UTC, someone235 requested changes

2023-10-24 07:47 UTC, someone235 approved these changes

2023-10-24 07:47 UTC, merged