TN11 -- various fixes concluded from ongoing internal experiment
kaspanet/rusty-kaspa pull request #320
Opened 2023-11-12 19:40 UTC by michaelsutton

2023-11-12 20:53 UTC, coderofstuff commented on consensus/src/processes/traversal_manager.rs
> +            if !return_anticone_only || !self.reachability_service.is_dag_ancestor_of(block, current) {
For code clarity, can we do:
```
let is_block_anticone_of_current = !self.reachability_service.is_dag_ancestor_of(block, current);

if !return_anticone_only || is_block_anticone_of_current {
  output.push(current);
}
```

It'd make it easier for whoever is reading this to understand the intent with self-documenting code.

2023-11-13 15:49 UTC, someone235 requested changes

2023-11-13 15:49 UTC, someone235 commented on protocol/flows/src/v5/ibd/flow.rs
>                  Payload::RequestAnticone,
Maybe change to `RequestAntiPast` and add a comment in the proto file that old versions can return only anticone?

2023-11-13 15:49 UTC, someone235 commented on testing/integration/src/common/client_notify.rs
> +    pub sender: Sender<Notification>,
I would make it private (accessible only via `new`)

2023-11-14 19:41 UTC, coderofstuff commented on consensus/src/processes/pruning_proof/mod.rs
> +    pub(crate) fn get_ghostdag_chain_k_depth(&self, hash: Hash) -> Vec<Hash> {
Do we need this specifically to be just about `get_ghostdag_chain_k_depth`? A generic `get_ghostdag_chain_with_depth(&self, hash: Hash, depth: u64)` may make it useful for other possible use-cases, like if we ever need to dig deeper.

2023-11-14 21:12 UTC, someone235 requested changes

2023-11-14 21:12 UTC, someone235 commented on protocol/flows/src/v6/request_pruning_point_and_anticone.rs
> +                            BlockWithTrustedDataV4Message { block: Some((&block).into()), ..Default::default() },
Add TODO in the proto file to remove the indices fields once v5 is obsolete

2023-11-14 21:12 UTC, someone235 commented on protocol/flows/src/v6/request_pruning_point_and_anticone.rs
> +                            BlockWithTrustedDataV4Message { block: Some((&block).into()), ..Default::default() },
Add TODO in the proto file to remove the indices fields once v5 is obsolete

2023-11-15 17:32 UTC, someone235 approved these changes

2023-11-15 17:33 UTC, merged