Request DB reset when TN11 restart is detected
kaspanet/rusty-kaspa pull request #331
Opened 2023-11-22 05:53 UTC by coderofstuff

This detects if the current TN11 Genesis is in the consensus DB - which it always should be. If it isn't, then TN11 has restarted and the DB must be deleted.

2023-11-22 09:17 UTC, someone235 requested changes

2023-11-22 19:57 UTC, coderofstuff commented on kaspad/src/daemon.rs
> +                if consensus_db
@someone235 do you mean something more like this?

```
                let consensus_db = kaspa_database::prelude::ConnBuilder::default()
                    .with_db_path(consensus_db_dir.clone().join(dir_name))
                    .with_files_limit(1)
                    .build()
                    .unwrap();

                let consensus_storage = ConsensusStorage::new(consensus_db, config.clone());

                if consensus_storage.headers_store.has(config.genesis.hash) {
                    trace!("Genesis is found in active consensus DB. No action needed.");
                }
```

2023-11-22 20:13 UTC, someone235 commented on kaspad/src/daemon.rs
> +                if consensus_db
I thought about using `DbHeadersStore::new`

2023-11-22 20:27 UTC, coderofstuff commented on kaspad/src/daemon.rs
> +                if consensus_db
Ahh, right, I can actually just use that directly. Thanks:

```
                let consensus_db = kaspa_database::prelude::ConnBuilder::default()
                    .with_db_path(consensus_db_dir.clone().join(dir_name))
                    .with_files_limit(1)
                    .build()
                    .unwrap();

                let headers_store = DbHeadersStore::new(consensus_db, 0);

                if headers_store.has(config.genesis.hash) {
                    trace!("Genesis is found in active consensus DB. No action needed.");
                }
```

2023-11-23 02:37 UTC, coderofstuff commented on kaspad/src/daemon.rs
> +    if args.testnet && args.testnet_suffix == 11 {
`args.mainnet` doesn't seem to be in args. Maybe `if args.testnet || args.simnet || args.devnet`?

2023-11-28 12:17 UTC, someone235 approved these changes

2023-11-28 12:51 UTC, merged