CLI watch-only account implementation
kaspanet/rusty-kaspa pull request #470
Opened 2024-05-07 22:45 UTC by 1bananagirl

The new account type watch-only supports:

- bip32
- multisig

Changes:

- print the extended public key for the command "export mnemonic" like it is in the golang kaspwallet
- added handling of keyless accounts in _select_account_with_args_ and _list_ functions
- watch-only and xpub text hints added to the _list_ function to differentiate account type

Future:

- creating unsigned transactions with watch-only wallets

2024-05-08 06:34 UTC, biryukovmaxim requested changes

2024-05-08 06:34 UTC, biryukovmaxim commented on cli/src/wizards/account.rs
> +    }
should be part of multisig import functionality

2024-05-08 06:34 UTC, biryukovmaxim commented on wallet/core/src/account/variants/watchonly.rs
> +}
make watch only acc only suitable for a single acc

2024-05-08 06:46 UTC, aspect commented on cli/src/cli.rs
> +                if xpubs.len() > 1 {
I actually gave that guidance as I think that it is better to be explicit about the purpose of the account. But you are right as multisig is technically a watch account by default.  Perhaps the account kind should then be explicit, as in "bip32-watch"?

2024-05-16 19:21 UTC, 1bananagirl commented
Thanks for you review Maxim!

## Refactoring

I've renamed the watch-only account to bip32-watch and removed multisig polymorphism, thus multisig watch-only remaining solely in the multisig account.

I've followed aspect's advice to add a helper function in the wallet module to format XPUB export according to network.

The new helper function is triggered by providing a new type TaggedXpub that is a pair formed of an extended public key and the network ID.

Inside the bip32 prefix submodule resides a new converter to get the right prefix for a given network.

### Account feature trait

The notion of feature was added to the account trait as a fn, defaulting to Option None, and is implemented in Bip32Watch and Multisig/watch-only to return a string giving an indication on the special feature of an account - which is watch-only in our case - an indication used to highlight that feature in the list and details commands output.

That step was necessary for the iterator filtering in details and list commands to be simple stupid finding out which account without private keys to consider printing.

### Commands

CLI commands for importing watch-only accounts now look like this:

```
   account import bip32-watch
   account import multisig-watch
```

I'm open to switch this to "account create" if needed.

I've found it more efficient to make a new parameter "multisig-watch" instead of bypassing "account create multisig", but if you insist, I can make that work instead.


### Output

The display of xpubs for watch-only account has been moved from the CLI list command output to the details output in order to not clutter the list view.

According to the currently selected network, the xpubs are now formatted with the appropriate prefix.

2024-06-13 23:16 UTC, aspect approved these changes
This looks good.  We are going to need to rebase this against wRPC serialization PR (once it is merged) before merging this PR.

2024-07-22 23:46 UTC, aspect commented
Merged into #506

2024-07-22 23:46 UTC, closed without merging