rothschild: donate funds to external address
kaspanet/rusty-kaspa pull request #482
Opened 2024-06-02 16:21 UTC by demisrael

2024-09-20 05:54 UTC, coderofstuff approved these changes

2024-09-20 05:58 UTC, coderofstuff requested changes
Code works as expected for send address and priority fee

minor comment

2024-09-20 05:58 UTC, coderofstuff commented on rothschild/src/main.rs
> +    info!("Using Rothschild with private key {} and address {}\n\tspend to {}", schnorr_key.display_secret(), String::from(&kaspa_addr), String::from(&kaspa_to_addr));
Since there's enough data being displayed here, probably split these into 3 lines

2024-09-20 14:08 UTC, demisrael commented on rothschild/src/main.rs
> +    info!("Using Rothschild with private key {} and address {}\n\tspend to {}", schnorr_key.display_secret(), String::from(&kaspa_addr), String::from(&kaspa_to_addr));
Done.

2024-09-22 03:22 UTC, coderofstuff approved these changes

2024-09-23 05:02 UTC, merged