feat: add signMessageWithoutRand method for kaspa wasm
kaspanet/rusty-kaspa pull request #587
Opened 2024-11-03 15:41 UTC by witter-deland

#586

2024-11-04 03:26 UTC, witter-deland commented
https://github.com/kasware-wallet/extension/pull/5

2024-11-05 01:40 UTC, coderofstuff commented
Signing without aux rand is dangerous and can leak keys.

2024-11-05 03:20 UTC, apoelstra commented
>Signing without aux rand is dangerous and can leak keys.

This is completely untrue.

2024-11-05 05:35 UTC, coderofstuff commented
> > Signing without aux rand is dangerous and can leak keys.
> 
> This is completely untrue.

Can you elaborate? I'm not familiar with the underlying implementation here but I'm mainly concerned with this leading to nonce reuse.

2024-11-05 08:31 UTC, elichai commented
Andrew is obviously right :) 
The auxiliary randomness exist only to mitigate specific kinds of power analysis side-channel attacks,
Providing it definitely improves security, but omitting it should not be considered dangerous, as most legacy signature schemes don't provide mitigations against such attacks,

To read more about the relevant discussions that arised in adding this randomness please see: https://github.com/sipa/bips/issues/195

2024-11-05 16:15 UTC, coderofstuff commented
> Andrew is obviously right :) The auxiliary randomness exists only to mitigate specific kinds of power analysis side-channel attacks, Providing it definitely improves security, but omitting it should not be considered dangerous, as most legacy signature schemes don't provide mitigations against such attacks,
> 
> To read more about the relevant discussions that arised in adding this randomness please see: [sipa/bips#195](https://github.com/sipa/bips/issues/195)

Thanks for the input @elichai.

@witter-deland I've reopened the PR while I read up more onto this.

2024-11-06 01:21 UTC, witter-deland commented
@coderofstuff Thanks
@elichai @apoelstra Thank you both for participating in the discussion

> > Andrew is obviously right :) The auxiliary randomness exists only to mitigate specific kinds of power analysis side-channel attacks, Providing it definitely improves security, but omitting it should not be considered dangerous, as most legacy signature schemes don't provide mitigations against such attacks,
> > To read more about the relevant discussions that arised in adding this randomness please see: [sipa/bips#195](https://github.com/sipa/bips/issues/195)
> 
> Thanks for the input @elichai.
> 
> @witter-deland I've reopened the PR while I read up more onto this.

2024-11-13 11:09 UTC, witter-deland commented
Excuse me. What's going on? This API is very straightforward. Are there any issues that are blocking the merge? Thank you.

2024-11-13 18:07 UTC, coderofstuff requested changes
Apologies for the delay, we're currently packed with other things.

The change itself looks sound. I just have some comments on code duplication.

2024-11-13 19:05 UTC, witter-deland commented
fixed :)
> Apologies for the delay, we're currently packed with other things.
> 
> The change itself looks sound. I just have some comments on code duplication.

2024-11-14 06:04 UTC, coderofstuff requested changes

2024-11-14 06:04 UTC, coderofstuff commented on wallet/core/src/wasm/message.rs
> +    noAuxRand: boolean;
Please make this optional here. This ensure any existing usage when this is added

2024-11-14 06:04 UTC, coderofstuff commented on wallet/core/src/wasm/message.rs
> +        let no_aux_rand = object.get_bool("noAuxRand")?;
If not passed, this should default to `false`

2024-11-14 07:03 UTC, coderofstuff submitted a review, later dismissed
LGTM. Tested the scenarios and existing demo still works.

As a follow-up, please update the `wasm/examples/nodejs/javascript/general/message-signing.js` to include a demo of the new scenario you added support for (passing `noAuxRand: true`)

2024-11-14 07:13 UTC, witter-deland commented
Sure, done :)
> LGTM. Tested the scenarios and existing demo still works.
> 
> As a follow-up, please update the `wasm/examples/nodejs/javascript/general/message-signing.js` to include a demo of the new scenario you added support for (passing `noAuxRand: true`)

2024-11-14 07:31 UTC, coderofstuff approved these changes
Thanks for that!

2024-11-14 08:36 UTC, merged