Add config to keep some extra days of data
kaspanet/rusty-kaspa pull request #592
Opened 2024-11-11 08:12 UTC by coderofstuff

2024-12-12 14:50 UTC, KaffinPX commented
Instead of days why dont we keep it by pruning points, would be a more convenient way(for future archival p2p features).

2024-12-16 05:09 UTC, coderofstuff commented
Changes to apply:
- Instead of extra days, allow specifying exactly how many days to keep
- Track the history root independent of pruning point

2025-02-17 20:43 UTC, michaelsutton commented
> Changes to apply:
> 
> * Instead of extra days, allow specifying exactly how many days to keep
> * Track the history root independent of pruning point
---
1. Also, search for the new history root from the bottom-up. 
2. You might need to add another DB tracking field in addition to history root: `source` (or a better name). 
Flow:
- find new source (by walking up from current source and up the chain)
- set source = new source (right before prune starts)
- prune
- set history root = source

This way the code can safely use `source` in places where data validity is required (e.g., get_source).
In `recover_pruning_workflows_if_needed` the condition for recovery should change to `if history_root != source`

2025-02-17 20:54 UTC, michaelsutton commented
> Instead of days why dont we keep it by pruning points, would be a more convenient way(for future archival p2p features)?

This might be a good idea, but we can apply this change later. I still think the cmd arg should be number of days to keep, and we can later translate that to the closest pruning point. 

Btw, perhaps we should log on start-up with warning about approximate max disk usage (for transient data) given the requested days.

2025-03-09 23:50 UTC, michaelsutton requested changes

2025-03-09 23:50 UTC, michaelsutton commented on kaspad/src/args.rs
> +            retention_period_days: 3.0,
seems like this will default to 3 days (or am I missing something?), while we want to default to the usual pruning point

2025-03-09 23:50 UTC, michaelsutton commented on consensus/src/pipeline/pruning_processor/processor.rs
> +    fn advance_retention_period_root(&self, retention_period_root: Hash, pruning_point: Hash) -> Hash {
in theory we can now simplify this by iterating through the new pruning samples store from the new pruning point to the prev retention root and searching for the first point with enough days above it. This will fulfill @KaffinPX's request to always have a pruning point as retention root and the code is also very simple to write (+ iteration is efficient and iterates very few steps since we are jumping between samples only).

2025-03-09 23:50 UTC, michaelsutton commented on consensus/src/consensus/mod.rs
> +        let source_score = self.headers_store.get_compact_header_data(self.get_retention_root()).unwrap().daa_score;
are we keeping `source` as a name in other places as well?

2025-03-09 23:53 UTC, coderofstuff commented on consensus/src/consensus/mod.rs
> +        let source_score = self.headers_store.get_compact_header_data(self.get_retention_root()).unwrap().daa_score;
No, I just forgot to replace this one.

2025-03-11 04:32 UTC, coderofstuff commented on kaspad/src/args.rs
> +            retention_period_days: 3.0,
It will default to 3 days, which is to keep what we currently have. But setting it to 0 as the default and staying with usual pruning depth is fine too as the default. We can inform users that they can set `--retention-period-days=3` if they want to keep more days of data.

2025-03-11 05:11 UTC, coderofstuff commented on consensus/src/pipeline/pruning_processor/processor.rs
> +    fn advance_retention_period_root(&self, retention_period_root: Hash, pruning_point: Hash) -> Hash {
Say someone sets retention period days to 300 days:

At 10bps, pruning point moves every 12hrs roughly. In that timeframe, that's 432000 blocks in that period. Assuming even only 1/10 of those are chain blocks - a forward chain iteration from retention root to the next pruning point still takes 43,200 steps.

In contrast a pruning point move where the iterations goes through pruning point samples only starting from the new pruning point will take ~600 steps to reach the new retention root (300 days, 2 pruning points per day).

Conclusion: yes, I agree with the above approach.

2025-03-11 11:50 UTC, michaelsutton commented on consensus/src/pipeline/pruning_processor/processor.rs
> +            let timestamp = self.headers_store.get_compact_header_data(block).unwrap().timestamp;
nit: we have `headers_store.get_timestamp`

2025-03-11 11:50 UTC, michaelsutton commented on consensus/core/src/config/mod.rs
> +    pub retention_period_days: f64,
my personal preference is that we make this an `Option` (as well as the cmd arg too) and explicitly handle the `None` case in pruning processor by directly setting the retention root as the pruning point. This makes it easier for me to verify that the changes do not affect the default way of using a node and thus reduces risks to zero.

2025-03-11 11:50 UTC, michaelsutton commented on kaspad/src/args.rs
> +            retention_period_days: 3.0,
see my other comment

2025-03-12 11:27 UTC, michaelsutton commented
Opened a PR over this branch with a few more essential leftover fixes I noticed (especially note the DB upgrade for archival cases): https://github.com/coderofstuff/rusty-kaspa/pull/19

2025-03-12 18:04 UTC, michaelsutton approved these changes

2025-03-12 18:30 UTC, michaelsutton commented
Ran some custom simpa tests with the following diff (and archival switched on and off). All looking good.

command line: `cargo run --release --bin simpa -- -n=6000 -t=1 --test-pruning --loglevel=info`

```diff
git diff
diff --git a/consensus/src/pipeline/pruning_processor/processor.rs b/consensus/src/pipeline/pruning_processor/processor.rs
index 923df58c5..c363c2eaa 100644
--- a/consensus/src/pipeline/pruning_processor/processor.rs
+++ b/consensus/src/pipeline/pruning_processor/processor.rs
@@ -205,6 +205,10 @@ impl PruningProcessor {
             // Inform the user
             info!("Periodic pruning point movement: advancing from {} to {}", current_pruning_info.pruning_point, new_pruning_point);
 
+            let virtual_daa_score = self.lkg_virtual_state.load().daa_score;
+            let retention_daa_score = self.headers_store.get_daa_score(adjusted_retention_period_root).unwrap();
+            warn!("VVVVVVVVVVVVVVVVVVV {}", virtual_daa_score - retention_daa_score);
+
             // Advance the pruning point utxoset to the state of the new pruning point using chain-block UTXO diffs
             if !self.advance_pruning_utxoset(current_pruning_info.pruning_point, new_pruning_point) {
                 info!("Interrupted while advancing the pruning point UTXO set: Process is exiting");
@@ -563,7 +567,11 @@ impl PruningProcessor {
                 let retention_period_ms = (retention_period_days * 86400.0 * 1000.0).ceil() as u64;
 
                 // The target timestamp we would like to find a point below
-                let retention_period_root_ts_target = unix_now().saturating_sub(retention_period_ms);
+                let retention_period_root_ts_target = self
+                    .headers_store
+                    .get_timestamp(self.lkg_virtual_state.load().ghostdag_data.selected_parent)
+                    .unwrap()
+                    .saturating_sub(retention_period_ms);
 
                 // Iterate from the new pruning point to the prev retention root and search for the first point with enough days above it.
                 // Note that prev retention root is always a past pruning point, so we can iterate via pruning samples until we reach it.
diff --git a/simpa/src/main.rs b/simpa/src/main.rs
index 3021ee568..f7f5a3749 100644
--- a/simpa/src/main.rs
+++ b/simpa/src/main.rs
@@ -199,6 +199,8 @@ fn main_impl(mut args: Args) {
         .apply_args(|config| apply_args_to_perf_params(&args, &mut config.perf))
         .adjust_perf_params_to_consensus_params()
         .apply_args(|config| config.ram_scale = args.ram_scale)
+        .apply_args(|config| config.retention_period_days = Some(0.01))
+        // .set_archival()
         .skip_proof_of_work()
         .enable_sanity_checks();
     if !args.test_pruning {
```

2025-03-12 18:31 UTC, merged