calculate sig ops on fly
kaspanet/rusty-kaspa pull request #597
Opened 2024-11-14 18:02 UTC by biryukovmaxim

# Migrate to runtime signature operation counting

Changes signature operation counting from static analysis to runtime counting during script execution for improved accuracy.

## Key changes
- Add sig_op tracking fields to TxScriptEngine
- Remove static sig_op counting functions
- Count sig_ops during script execution 
- Add runtime checks for sig_op limits
- Add new error type for sig_op limit violations
- Update transaction validation to use runtime counting

## Breaking changes
- Changes sig_op validation timing from pre-execution to during execution
- May affect transaction fee estimation

## Todo
- [ ] Restore and update `test_get_sig_op_count` tests
- [ ] Add tests for sig_op limit edge cases and errors 
- [ ] Decide approach for P2SH sig_op limits in mempool standardness rules
- [ ] Add documentation for new sig_op runtime counting behavior
- [ ] Consider adding sig_op estimation helper for fee calculation

Requires manual testing and careful review of sig_op counting logic.

2025-02-01 21:38 UTC, someone235 requested changes

2025-02-01 21:38 UTC, someone235 commented on crypto/txscript/src/lib.rs
> +    pub fn sig_op_required(&self) -> Option<u8> {
sig_op->sig_ops
Also, maybe `used_sig_ops` is a better name?

2025-02-01 21:38 UTC, someone235 commented on crypto/txscript/src/lib.rs
> +            runtime_sig_op_counting: None, // todo?
I don't think it's needed, but explain why in a comment

2025-02-01 21:38 UTC, someone235 commented on crypto/txscript/src/lib.rs
> +        Multi(Vec<SignatureData>),
I think Multisig gives a clearer context. And also comment on each variant would be nice

2025-02-01 21:38 UTC, someone235 commented on crypto/txscript/src/lib.rs
> +        }
I think it would improve readability if `RuntimeSigOpCounter` would have a method that does all of this

2025-02-01 21:38 UTC, someone235 commented on crypto/txscript/src/lib.rs
> +                name: "Mixed Schnorr and ECDSA",
I think it's better not to repeat test names. In this case, adding " - Above limit" or " - Exceeds limit" would be helpful (same for similar tests)

2025-02-01 21:38 UTC, someone235 commented on crypto/txscript/src/opcodes/mod.rs
> +
Same comment about a method

2025-02-01 21:38 UTC, someone235 commented on crypto/txscript/src/opcodes/mod.rs
> +                }
Same comment about a method

2025-02-02 08:08 UTC, biryukovmaxim commented on crypto/txscript/src/lib.rs
> +    pub fn sig_op_required(&self) -> Option<u8> {
2175dbe5481c4e9e4ff375b2c1d8c7c435e05bfc

2025-02-02 08:09 UTC, biryukovmaxim commented on crypto/txscript/errors/src/lib.rs
> +    #[error("sig op count exceed passed limit of {1}")]
183e859ebf7ff31c0e45d0a7505d6b68a73df418

2025-02-02 08:09 UTC, biryukovmaxim commented on crypto/txscript/errors/src/lib.rs
> +    ExceededSigOpLimit(u16, u8),
183e859ebf7ff31c0e45d0a7505d6b68a73df418

2025-02-02 08:10 UTC, biryukovmaxim commented on crypto/txscript/src/lib.rs
> +pub fn get_sig_op_count_via_simulation<T: VerifiableTransaction, Reused: SigHashReusedValues>(
i was aiming to use it in test, but made them without the function.
the idea is adding some helper function that can return sig op count that is needed for execution by executing it with TxEngine help

2025-02-02 08:45 UTC, biryukovmaxim commented on crypto/txscript/src/lib.rs
> +            runtime_sig_op_counting: None, // todo?
6ba349b096f149002f4eb4ba2afaeb479b68273c

2025-02-02 08:46 UTC, biryukovmaxim commented on crypto/txscript/src/lib.rs
> +        Multi(Vec<SignatureData>),
dfc20f7043ceb6eb79633905b41a2a436b0031e5

2025-02-02 08:47 UTC, biryukovmaxim commented on crypto/txscript/src/opcodes/mod.rs
> +                }
78dfebd72d7e6a3c0bc0ac3bf410caf9218f7970

2025-02-02 08:47 UTC, biryukovmaxim commented on crypto/txscript/src/opcodes/mod.rs
> +
78dfebd72d7e6a3c0bc0ac3bf410caf9218f7970

2025-02-02 08:47 UTC, biryukovmaxim commented on crypto/txscript/src/lib.rs
> +        }
78dfebd72d7e6a3c0bc0ac3bf410caf9218f7970

2025-02-02 08:47 UTC, biryukovmaxim commented on crypto/txscript/src/lib.rs
> +                name: "Mixed Schnorr and ECDSA",
f032de3a7ae364278470a15aec4ebdd64c47e9b4

2025-02-02 21:11 UTC, someone235 commented on crypto/txscript/src/lib.rs
> +pub fn get_sig_op_count_via_simulation<T: VerifiableTransaction, Reused: SigHashReusedValues>(
If the function is only for tests, delete it since it's not used.

If you think it's somehow good for users, add documentation that explains what it does

2025-02-02 21:32 UTC, someone235 requested changes

2025-02-02 21:32 UTC, someone235 commented on crypto/txscript/src/lib.rs
>      pub sig_op_remaining: u8,
Maybe it shouldn't be `pub` anymore?

2025-02-02 21:32 UTC, someone235 commented on crypto/txscript/src/lib.rs
> +            num_sigs.try_into().map_err(|_| TxScriptError::NumberTooBig("Signatures count mustn't exceed 255".to_string()))?;
I had a suspicion that this can create a netsplit, since `num_sigs` arrived from the stack as `i32` so it can theoretically be bigger than 255. But after some reading of the context it seems that this error is actually unreachable, since `num_sigs` is bounded by `num_keys` which is bounded by `MAX_PUB_KEYS_PER_MUTLTISIG=20`.

But just to be sure, can you make a multisig test where the hardfork is inactive and `num_sigs=256`? I expect to see it fails with `Err(TxScriptError::InvalidPubKeyCount(format!("too many pubkeys {num_keys} > {MAX_PUB_KEYS_PER_MUTLTISIG}")))` or `Err(TxScriptError::InvalidSignatureCount(format!("more signatures than pubkeys {num_sigs} > {num_keys}")))`

2025-02-03 07:13 UTC, biryukovmaxim commented on crypto/txscript/src/lib.rs
> +            num_sigs.try_into().map_err(|_| TxScriptError::NumberTooBig("Signatures count mustn't exceed 255".to_string()))?;
actually it will face first  MAX_SCRIPT_ELEMENT_SIZE then MAX_STACK_SIZE and only after that, it will fail with error related to MAX_PUB_KEYS_PER_MUTLTISIG.

2025-02-03 08:32 UTC, biryukovmaxim commented on crypto/txscript/src/lib.rs
> +pub fn get_sig_op_count_via_simulation<T: VerifiableTransaction, Reused: SigHashReusedValues>(
4f14ee7e72c87f0523d8d20adcbb4590047f5766

2025-02-03 08:32 UTC, biryukovmaxim commented on crypto/txscript/src/lib.rs
>      pub sig_op_remaining: u8,
d23e817a777f25762696b75a7ecdff1762862369

2025-02-03 08:33 UTC, biryukovmaxim commented on crypto/txscript/src/lib.rs
> +            num_sigs.try_into().map_err(|_| TxScriptError::NumberTooBig("Signatures count mustn't exceed 255".to_string()))?;
7fedccaedf601971b284e7d0659576961835876f

2025-02-03 08:53 UTC, someone235 approved these changes

2025-02-03 14:21 UTC, michaelsutton commented on crypto/txscript/src/lib.rs
> +                .then_some(RuntimeSigOpCounter { sig_op_limit: input.sig_op_count, sig_op_remaining: input.sig_op_count }),
we should use `RuntimeSigOpCounter::new` to avoid the manual double mention of `input.sig_op_count` 
(nit: I'd say perhaps this is a reason to move `RuntimeSigOpCounter ` to an inner `mod` to avoid access to the private fields)

2025-02-03 14:28 UTC, michaelsutton commented
This is brilliant work btw.

2025-02-03 15:23 UTC, someone235 approved these changes

2025-02-03 15:50 UTC, michaelsutton commented on crypto/txscript/src/lib.rs
> +    let sig_cache = Cache::new(10_000);
although `get_sig_op_count` is not used in the current codebase, it seem redundant to actually allocate a cache here. I think `size` should be `0` here (there are no expected cache hits).

2025-02-03 15:56 UTC, michaelsutton approved these changes

2025-02-03 16:51 UTC, merged