Rpc
kaspanet/rusty-kaspa pull request #80
Opened 2022-11-16 15:37 UTC by tiram88

This is basically a copy of the code developed in [rpc-poly-prototype](https://github.com/tiram88/poly-rpc-prototype) with some minor adjustments, notably `Uint192` because of its use as `BlueWorkType`.

This PR features:
- Trait `RpcApi` (initial work of [Aspectron](https://github.com/aspectron/rusty-kaspa/blob/ffa8dd95264e68580acabb6cccb6a37dfd39c30a/rpc/core/src/client/interface.rs)) exposing a protocol-agnostic API
- rpc-core `RpcApi` server responsible for fetching data from consensus
- rpc-grpc `RpcApi` service and client implementing (partially) the `protowire` RPC from kaspad
- Notification system with following pipeline: consensus -> rpc-core server -> rpc-grpc service -> rpc-grpc client -> client code

## Limitations

The gRPC implementation at this stage should be considered essentially a proof of concept. It is limited to 2 queries: `get_block` and `get_info`.

The same is true of the notification system that only implements `BlockAdded`.

The whole rpc sub-system is not actually connected to consensus for now, neither for queries nor for notifications.

All these issues will have dedicated PRs.

2022-11-17 12:00 UTC, KaffinPX commented
plz no gRPC

2022-11-17 12:47 UTC, tiram88 commented
gRPC is the minimal RPC requirement for inter-operability and backwards compatibility. However, we have plans for 2 more protocols: borsh and json. So most probable use-cases should all be covered.

2022-11-22 16:29 UTC, someone235 requested changes

2022-11-22 16:29 UTC, someone235 commented on rpc/core/src/notify/subscriber.rs
> +    fn subscribe_task(&self, shutdown_trigger: triggered::Trigger, subscribe_rx: Receiver<SubscribeMessage>) {
subscribe_loop?

2022-11-22 16:29 UTC, someone235 commented on rpc/core/src/notify/subscriber.rs
> +        // let listener = self.listener.clone();
Can you remove comment?

2022-11-22 16:43 UTC, tiram88 commented on Cargo.toml
> +borsh = "0.9.3"
It is a perhaps good thing if we can do that.

But then what about Anton's ongoing development of the RPC borsh client/server?

2022-11-24 13:54 UTC, tiram88 reviewed
Thank you @someone235 for your review.

I addressed all issues. Quite a lot of changes, as expected.

2022-11-24 13:54 UTC, tiram88 commented on Cargo.toml
> +borsh = "0.9.3"
So as discussed yesterday, I remove borsh as a workspace dependency and keep it in rpc-core

2022-11-24 16:03 UTC, someone235 requested changes

2022-11-24 17:14 UTC, tiram88 reviewed
Everything addressed

2022-11-24 17:14 UTC, tiram88 commented on rpc/grpc/src/server/connection.rs
> +    _address: SocketAddr,
Fixed

2022-11-24 17:14 UTC, tiram88 commented on rpc/grpc/src/server/service.rs
> +    pub async fn finalize(&self) -> RpcResult<()> {
yes

2022-11-24 17:19 UTC, someone235 approved these changes

2022-11-24 19:30 UTC, merged